#!/usr/bin/env python3.11
"""Campus Voice Assistant — Whisper STT + Claude AI + edge-tts TTS
Campus commands (stop/next/volume) are executed immediately;
all responses generated by Claude for natural, intelligent replies.
"""
import os, sys, subprocess, tempfile, json, re, datetime, random, urllib.parse, threading

STATE_FILE = os.path.join(tempfile.gettempdir(), 'campus-voice-game-state.json')

WHISPER_MODEL = None

def _ollama_warmup():
    """Pre-load Ollama model into RAM so first user request is fast."""
    model = os.environ.get('OLLAMA_MODEL', '')
    host  = os.environ.get('OLLAMA_HOST', 'http://host.docker.internal:11434')
    if not model:
        return
    try:
        import urllib.request
        body = json.dumps({'model': model, 'keep_alive': '10m'}).encode()
        req = urllib.request.Request(f'{host}/api/generate', data=body,
            headers={'Content-Type': 'application/json'}, method='POST')
        with urllib.request.urlopen(req, timeout=120) as r:
            r.read()
    except Exception:
        pass

threading.Thread(target=_ollama_warmup, daemon=True).start()

def _load_model():
    global WHISPER_MODEL
    if WHISPER_MODEL is None:
        from faster_whisper import WhisperModel
        cache = os.path.join(os.environ.get('HF_HOME', os.path.expanduser('~/.cache')), 'faster_whisper')
        WHISPER_MODEL = WhisperModel('base', device='cpu', compute_type='int8', download_root=cache)
    return WHISPER_MODEL

def transcribe(audio_path: str) -> str:
    wav = audio_path
    if not audio_path.endswith('.wav'):
        wav = tempfile.mktemp(suffix='.wav')
        try:
            subprocess.run(
                ['ffmpeg', '-y', '-i', audio_path, '-ar', '16000', '-ac', '1', wav],
                capture_output=True, timeout=30
            )
        except Exception as e:
            return f'[ffmpeg error: {e}]'
    try:
        model = _load_model()
        segs, _ = model.transcribe(wav, beam_size=3)
        return ' '.join(s.text.strip() for s in segs).strip()
    except Exception as e:
        return f'[whisper error: {e}]'
    finally:
        if wav != audio_path and os.path.exists(wav):
            os.unlink(wav)

# ── Campus API helper ─────────────────────────────────────────────────────────
def _api(path, method='POST', data=None):
    import urllib.request
    url = f'http://localhost:8090{path}'
    body = json.dumps(data or {}).encode()
    req = urllib.request.Request(url, data=body,
                                  headers={'Content-Type': 'application/json'}, method=method)
    try:
        with urllib.request.urlopen(req, timeout=5) as r:
            return json.loads(r.read())
    except Exception:
        return {}

# ── Real-time data fetchers ───────────────────────────────────────────────────
def _fetch_weather(city: str = 'Baku') -> str:
    try:
        import urllib.request
        url = f'http://wttr.in/{urllib.parse.quote(city)}?format=j1'
        with urllib.request.urlopen(url, timeout=5) as r:
            d = json.loads(r.read())
        cur = d['current_condition'][0]
        desc = (cur.get('weatherDesc') or [{}])[0].get('value', '')
        return f"{cur['temp_C']}°C, ощущается {cur['FeelsLikeC']}°C, {desc}, влажность {cur['humidity']}%"
    except Exception:
        return ''

def _extract_city(t: str) -> str:
    """'погода в москве' -> 'Москва'. Пусто, если город не указан явно (тогда Баку)."""
    m = re.search(r'погод[а-я]*\s+в\s+([а-яё\-\s]+)', t)
    if not m:
        m = re.search(r'weather\s+in\s+([a-z\-\s]+)', t)
    if m:
        return m.group(1).strip().rstrip('?.!').title()
    return ''

def _fetch_wikipedia(query: str) -> str:
    try:
        import urllib.request
        url = f'https://ru.wikipedia.org/api/rest_v1/page/summary/{urllib.parse.quote(query)}'
        req = urllib.request.Request(url, headers={'User-Agent': 'campus-voice-assistant/1.0'})
        with urllib.request.urlopen(req, timeout=6) as r:
            d = json.loads(r.read())
        return (d.get('extract') or '').strip()
    except Exception:
        return ''

def _fetch_track() -> str:
    d = _api('/api/status', method='GET')
    return d.get('track') or d.get('title') or d.get('playing') or ''

# ── Keyword maps (for immediate campus actions) ───────────────────────────────
_STOP    = ['стоп', 'пауза', 'останови', 'заглуши', 'stop', 'pause']
_NEXT    = ['следующий трек', 'следующую', 'следующий', 'пропусти', 'next', 'skip']
_LOUDER  = ['громче', 'увеличь громкость', 'сделай громче', 'погромче']
_QUIETER = ['тише', 'убавь', 'потише', 'уменьши громкость', 'потише сделай']
_PLAY    = ['включи музыку', 'играй', 'воспроизведи', 'запусти музыку', 'давай музыку']
_WHAT    = ['что играет', 'что за трек', 'что за песня', 'какая песня', 'что сейчас играет']
_WEATHER = ['погода', 'температура', 'weather', 'градус', 'холодно', 'тепло на улице']
_RADIO   = ['включи радио', 'радио включи', 'radio']
_COIN    = ['подкинь монетку', 'подбрось монетку', 'монетка', 'орёл или решка', 'орел или решка']
_TWISTER = ['скороговорку', 'скороговорка']
_PARROT  = ['повтори за мной', 'повторяй за мной', 'будь попугаем', 'повтори как попугай']
_WIKI    = ['википедия', 'что такое', 'кто такой', 'кто такая', 'расскажи про', 'расскажи о']
_YOUTUBE = ['найди на ютубе', 'найди в ютубе', 'ютуб', 'youtube']
_MAPS    = ['открой карту', 'открой карты', 'покажи на карте', 'где находится']
_SITE    = ['открой сайт', 'открой браузер', 'зайди на сайт']
_GUESS_START = ['угадай число', 'загадай число', 'игра в числа']
_GUESS_TRY   = re.compile(r'\b(\d{1,4})\b')

def _match(t, kws):
    return any(k in t for k in kws)

# ── Простые детерминированные навыки (без ИИ — как в classic voice-assistant'ах) ──
_TWISTERS = [
    'Карл у Клары украл кораллы, а Клара у Карла украла кларнет.',
    'На дворе трава, на траве дрова.',
    'Ткёт ткач ткани на платки Тане.',
    'От топота копыт пыль по полю летит.',
    'Шла Саша по шоссе и сосала сушку.',
]

def _game_state_load() -> dict:
    try:
        with open(STATE_FILE) as f:
            return json.load(f)
    except Exception:
        return {}

def _game_state_save(state: dict):
    try:
        with open(STATE_FILE, 'w') as f:
            json.dump(state, f)
    except Exception:
        pass

# Многие API-шлюзы (Cloudflare и т.п.) банят стандартный User-Agent
# urllib.request ("Python-urllib/3.x") как бота — отсюда были 403.
_UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'

# ── AI call (Groq → Anthropic → Ollama fallback chain) ───────────────────────
def _ask_openai_compat(url: str, auth_header: str, model: str, system: str, user_text: str, timeout: int = 15) -> str:
    """Generic OpenAI-compatible chat completion call."""
    import urllib.request, urllib.error
    body = json.dumps({
        'model': model,
        'max_tokens': 300,
        'messages': [
            {'role': 'system', 'content': system},
            {'role': 'user', 'content': user_text},
        ]
    }).encode()
    req = urllib.request.Request(url, data=body,
        headers={'Authorization': auth_header, 'Content-Type': 'application/json', 'User-Agent': _UA},
        method='POST')
    with urllib.request.urlopen(req, timeout=timeout) as r:
        d = json.loads(r.read())
    return d['choices'][0]['message']['content'].strip()

def _ask_ai(user_text: str, system: str) -> str:
    # 1) Google Gemini (free tier, no regional block)
    gemini_key = os.environ.get('GEMINI_API_KEY', '')
    if gemini_key:
        try:
            import urllib.request
            url = f'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={gemini_key}'
            body = json.dumps({
                'system_instruction': {'parts': [{'text': system}]},
                'contents': [{'parts': [{'text': user_text}]}],
                'generationConfig': {'maxOutputTokens': 300, 'temperature': 0.7}
            }).encode()
            req = urllib.request.Request(url, data=body,
                headers={'Content-Type': 'application/json', 'User-Agent': _UA}, method='POST')
            with urllib.request.urlopen(req, timeout=15) as r:
                d = json.loads(r.read())
            return d['candidates'][0]['content']['parts'][0]['text'].strip()
        except Exception as e:
            print(f'Gemini error: {e}', file=sys.stderr)

    # 2) Groq (реально основной провайдер сейчас - Gemini без квоты, Anthropic без ключа)
    groq_key = os.environ.get('GROQ_API_KEY', '')
    if groq_key:
        try:
            return _ask_openai_compat(
                'https://api.groq.com/openai/v1/chat/completions',
                f'Bearer {groq_key}', 'llama-3.3-70b-versatile', system, user_text)
        except Exception as e:
            print(f'Groq error: {e}', file=sys.stderr)

    # 3) Anthropic Claude
    anthropic_key = os.environ.get('ANTHROPIC_API_KEY', '')
    if anthropic_key:
        try:
            import urllib.request
            body = json.dumps({
                'model': 'claude-haiku-4-5-20251001', 'max_tokens': 300,
                'system': system,
                'messages': [{'role': 'user', 'content': user_text}]
            }).encode()
            req = urllib.request.Request('https://api.anthropic.com/v1/messages', data=body,
                headers={'x-api-key': anthropic_key, 'anthropic-version': '2023-06-01',
                         'content-type': 'application/json', 'User-Agent': _UA}, method='POST')
            with urllib.request.urlopen(req, timeout=15) as r:
                d = json.loads(r.read())
            return d['content'][0]['text'].strip()
        except Exception as e:
            print(f'Anthropic error: {e}', file=sys.stderr)

    # 4) Ollama (local, no internet needed)
    ollama_model = os.environ.get('OLLAMA_MODEL', '')
    if ollama_model:
        try:
            ollama_host = os.environ.get('OLLAMA_HOST', 'http://host.docker.internal:11434')
            return _ask_openai_compat(
                f'{ollama_host}/v1/chat/completions',
                'Bearer ollama', ollama_model, system, user_text, timeout=60)
        except Exception as e:
            print(f'Ollama error: {e}', file=sys.stderr)

    return ''

# ── Simple fallback (no API key) ──────────────────────────────────────────────
def _simple_reply(text: str, action: str, extra: str = '') -> str:
    if action == 'stop':    return 'Музыка остановлена.'
    if action == 'next':    return 'Переключаю на следующий трек.'
    if action == 'vol_up':  return 'Громкость увеличена.'
    if action == 'vol_down':return 'Громкость уменьшена.'
    if action == 'play':    return 'Включаю музыку.'
    if action == 'what':    return f'Сейчас играет: {extra}.' if extra else 'Музыка не воспроизводится.'
    hour = datetime.datetime.now().hour
    greet = 'Доброе утро' if hour < 12 else ('Добрый день' if hour < 18 else 'Добрый вечер')
    return f'{greet}! Для умных ответов добавьте ANTHROPIC_API_KEY в .env файл.'

# ── Main command processor ────────────────────────────────────────────────────
def process_command(text: str, campus: str = 'both') -> dict:
    t = text.lower().strip()
    action = None
    action_extra = ''
    open_url = None

    # ── Игра "угадай число": если игра уже идёт — сначала проверяем попытку ──
    state = _game_state_load()
    if state.get('game') == 'guess_number':
        m = _GUESS_TRY.search(t)
        if m:
            guess = int(m.group(1))
            target = state['target']
            state['attempts'] = state.get('attempts', 0) + 1
            if guess == target:
                _game_state_save({})
                return {'action': 'game',
                        'reply': f'Верно! Загадано было {target}. Угадали за {state["attempts"]} попыток.'}
            _game_state_save(state)
            hint = 'больше' if guess < target else 'меньше'
            return {'action': 'game', 'reply': f'Мимо. Загаданное число {hint}, чем {guess}. Попробуйте ещё раз.'}

    # ── Детерминированные навыки (без обращения к ИИ) ──
    if _match(t, _GUESS_START):
        target = random.randint(1, 100)
        _game_state_save({'game': 'guess_number', 'target': target, 'attempts': 0})
        return {'action': 'game', 'reply': 'Загадал число от 1 до 100. Попробуйте угадать!'}

    if _match(t, _COIN):
        result = random.choice(['Орёл', 'Решка'])
        return {'action': 'coin', 'reply': f'{result}!'}

    if _match(t, _TWISTER):
        return {'action': 'twister', 'reply': random.choice(_TWISTERS)}

    if _match(t, _PARROT):
        return {'action': 'parrot', 'reply': 'Хорошо, я попугай! Скажите что-нибудь ещё раз.'}

    if _match(t, _SITE):
        m = re.search(r'сайт\s+([a-zа-яё0-9.\-]+)', t)
        site = m.group(1) if m else None
        if site:
            if '.' not in site:
                site += '.com'
            open_url = 'https://' + site
            return {'action': 'open_url', 'open_url': open_url, 'reply': f'Открываю сайт {site}.'}
        return {'action': 'open_url', 'open_url': 'https://google.com', 'reply': 'Открываю браузер.'}

    if _match(t, _YOUTUBE):
        q = re.sub('|'.join(_YOUTUBE), '', t).strip() or text
        open_url = 'https://www.youtube.com/results?search_query=' + urllib.parse.quote(q)
        return {'action': 'open_url', 'open_url': open_url, 'reply': f'Ищу на YouTube: {q}.'}

    if _match(t, _MAPS):
        q = re.sub('|'.join(_MAPS), '', t).strip()
        if q:
            open_url = 'https://www.openstreetmap.org/search?query=' + urllib.parse.quote(q)
            reply = f'Открываю карту: {q}.'
        else:
            open_url = 'https://www.openstreetmap.org/#map=12/40.4093/49.8671'  # Баку
            reply = 'Открываю карту.'
        return {'action': 'open_url', 'open_url': open_url, 'reply': reply}

    if _match(t, _RADIO):
        _api('/api/play-radio', data={'campus': campus, 'station': 'europa_plus'})
        return {'action': 'radio', 'reply': 'Включаю радио.'}

    # Execute campus control commands immediately (before Claude call)
    if _match(t, _STOP):
        _api('/api/stop')
        action = 'stop'
    elif _match(t, _NEXT):
        _api('/api/next')
        action = 'next'
    elif _match(t, _LOUDER):
        _api('/api/vol', data={'delta': 10, 'campus': campus})
        action = 'vol_up'
    elif _match(t, _QUIETER):
        _api('/api/vol', data={'delta': -10, 'campus': campus})
        action = 'vol_down'
    elif _match(t, _PLAY):
        _api('/api/play_random', data={'campus': campus})
        action = 'play'
    elif _match(t, _WHAT):
        action_extra = _fetch_track()
        action = 'what'

    # Build real-time context for Claude
    now = datetime.datetime.now()
    months_ru = ['января','февраля','марта','апреля','мая','июня',
                 'июля','августа','сентября','октября','ноября','декабря']
    ctx_lines = [
        f'Дата и время: {now.day} {months_ru[now.month-1]} {now.year}, {now.strftime("%H:%M")}.',
        'Местоположение: Баку, Азербайджан.',
    ]
    if _match(t, _WEATHER):
        city = _extract_city(t) or 'Baku'
        w = _fetch_weather(city)
        if w:
            ctx_lines.append(f'Актуальная погода в {city}: {w}.')
    if _match(t, _WIKI):
        q = text
        for kw in _WIKI:
            q = re.sub(kw, '', q, flags=re.IGNORECASE)
        q = q.strip(' ?.,')
        if q:
            wiki = _fetch_wikipedia(q)
            if wiki:
                ctx_lines.append(f'Из энциклопедии про "{q}": {wiki[:500]}')
    if action == 'what' and action_extra:
        ctx_lines.append(f'Сейчас в кампусе играет: {action_extra}.')
    elif action == 'what' and not action_extra:
        ctx_lines.append('Музыка в кампусе сейчас не воспроизводится.')
    if action and action != 'what':
        action_map = {
            'stop': 'Музыка остановлена.',
            'next': 'Переключено на следующий трек.',
            'vol_up': 'Громкость увеличена.',
            'vol_down': 'Громкость уменьшена.',
            'play': 'Музыка включена.',
        }
        ctx_lines.append(f'Только что выполнено: {action_map.get(action, "")}')

    system_prompt = (
        'Ты голосовой помощник умного кампуса в Баку — умный, дружелюбный, как Алиса от Яндекса. '
        'ВАЖНО: отвечай ТОЛЬКО на русском языке. Никаких китайских, арабских, азербайджанских или других иностранных слов — только русский. '
        'Ответ должен быть коротким: 1-3 предложения максимум. '
        'Ты можешь отвечать на любые вопросы: погода, время, факты, шутки, математика, перевод текста — всё что угодно. '
        'НЕ используй HTML теги, эмодзи, markdown — твои ответы озвучиваются голосом. '
        'Если тебе только что выполнили команду (стоп, следующий, громче и т.д.) — '
        'подтверди это естественным образом и можешь добавить что-то полезное. '
        'Если в контексте есть статья из энциклопедии — перескажи суть своими словами кратко. '
        '\n\nКонтекст:\n' + '\n'.join(ctx_lines)
    )

    reply = _ask_ai(text, system_prompt)
    if not reply:
        reply = _simple_reply(text, action, action_extra)

    result = {'action': action or 'ai', 'reply': reply}
    if open_url:
        result['open_url'] = open_url
    return result

# ── TTS ───────────────────────────────────────────────────────────────────────
TTS_VOICE = 'ru-RU-SvetlanaNeural'

def tts(text: str, out_path: str) -> bool:
    clean = re.sub(r'<[^>]+>', '', text).strip()
    clean = re.sub(r'[^\w\s.,!?;:\'\"()\-–—а-яёА-ЯЁa-zA-Z0-9]', ' ', clean).strip()
    if not clean:
        return False
    try:
        import asyncio, edge_tts
        async def _gen():
            c = edge_tts.Communicate(clean, voice=TTS_VOICE, rate='+5%')
            await c.save(out_path)
        asyncio.run(_gen())
        return os.path.exists(out_path) and os.path.getsize(out_path) > 500
    except Exception as e:
        print(f'TTS error: {e}', file=sys.stderr)
        return False

# ── Entry point ───────────────────────────────────────────────────────────────
def handle_voice(audio_path: str, campus: str = 'both') -> dict:
    text = transcribe(audio_path)
    if text.startswith('[') and 'error' in text:
        return {'ok': False, 'text': '', 'reply': f'Ошибка распознавания речи.'}
    result = process_command(text, campus)
    result['ok'] = True
    result['text'] = text
    return result

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: voice_cmd.py <audio_file> [campus]')
        sys.exit(1)
    r = handle_voice(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else 'both')
    print(json.dumps(r, ensure_ascii=False, indent=2))
