#!/usr/bin/env python3.11
"""Campus Voice Assistant — Whisper STT + Claude AI + edge-tts TTS
Campus commands (stop/next/volume) are executed immediately;
all responses generated by Claude for natural, intelligent replies.
"""
import os, sys, subprocess, tempfile, json, re, datetime, threading

WHISPER_MODEL = None

def _ollama_warmup():
    """Pre-load Ollama model into RAM so first user request is fast."""
    model = os.environ.get('OLLAMA_MODEL', '')
    host  = os.environ.get('OLLAMA_HOST', 'http://host.docker.internal:11434')
    if not model:
        return
    try:
        import urllib.request
        body = json.dumps({'model': model, 'keep_alive': '10m'}).encode()
        req = urllib.request.Request(f'{host}/api/generate', data=body,
            headers={'Content-Type': 'application/json'}, method='POST')
        with urllib.request.urlopen(req, timeout=120) as r:
            r.read()
    except Exception:
        pass

threading.Thread(target=_ollama_warmup, daemon=True).start()

def _load_model():
    global WHISPER_MODEL
    if WHISPER_MODEL is None:
        from faster_whisper import WhisperModel
        cache = os.path.join(os.environ.get('HF_HOME', os.path.expanduser('~/.cache')), 'faster_whisper')
        WHISPER_MODEL = WhisperModel('base', device='cpu', compute_type='int8', download_root=cache)
    return WHISPER_MODEL

def transcribe(audio_path: str) -> str:
    wav = audio_path
    if not audio_path.endswith('.wav'):
        wav = tempfile.mktemp(suffix='.wav')
        try:
            subprocess.run(
                ['ffmpeg', '-y', '-i', audio_path, '-ar', '16000', '-ac', '1', wav],
                capture_output=True, timeout=30
            )
        except Exception as e:
            return f'[ffmpeg error: {e}]'
    try:
        model = _load_model()
        segs, _ = model.transcribe(wav, beam_size=3)
        return ' '.join(s.text.strip() for s in segs).strip()
    except Exception as e:
        return f'[whisper error: {e}]'
    finally:
        if wav != audio_path and os.path.exists(wav):
            os.unlink(wav)

# ── Campus API helper ─────────────────────────────────────────────────────────
def _api(path, method='POST', data=None):
    import urllib.request
    url = f'http://localhost:8090{path}'
    body = json.dumps(data or {}).encode()
    req = urllib.request.Request(url, data=body,
                                  headers={'Content-Type': 'application/json'}, method=method)
    try:
        with urllib.request.urlopen(req, timeout=5) as r:
            return json.loads(r.read())
    except Exception:
        return {}

# ── Real-time data fetchers ───────────────────────────────────────────────────
def _fetch_weather() -> str:
    try:
        import urllib.request
        with urllib.request.urlopen('http://wttr.in/Baku?format=j1', timeout=5) as r:
            d = json.loads(r.read())
        cur = d['current_condition'][0]
        desc = (cur.get('weatherDesc') or [{}])[0].get('value', '')
        return f"{cur['temp_C']}°C, ощущается {cur['FeelsLikeC']}°C, {desc}, влажность {cur['humidity']}%"
    except Exception:
        return ''

def _fetch_track() -> str:
    d = _api('/api/status', method='GET')
    return d.get('track') or d.get('title') or d.get('playing') or ''

# ── Keyword maps (for immediate campus actions) ───────────────────────────────
_STOP    = ['стоп', 'пауза', 'останови', 'заглуши', 'stop', 'pause']
_NEXT    = ['следующий трек', 'следующую', 'следующий', 'пропусти', 'next', 'skip']
_LOUDER  = ['громче', 'увеличь громкость', 'сделай громче', 'погромче']
_QUIETER = ['тише', 'убавь', 'потише', 'уменьши громкость', 'потише сделай']
_PLAY    = ['включи музыку', 'играй', 'воспроизведи', 'запусти музыку', 'давай музыку']
_WHAT    = ['что играет', 'что за трек', 'что за песня', 'какая песня', 'что сейчас играет']
_WEATHER = ['погода', 'температура', 'weather', 'градус', 'холодно', 'тепло на улице']

def _match(t, kws):
    return any(k in t for k in kws)

# ── AI call (Groq → Anthropic → Ollama fallback chain) ───────────────────────
def _ask_openai_compat(url: str, auth_header: str, model: str, system: str, user_text: str, timeout: int = 15) -> str:
    """Generic OpenAI-compatible chat completion call."""
    import urllib.request, urllib.error
    body = json.dumps({
        'model': model,
        'max_tokens': 300,
        'messages': [
            {'role': 'system', 'content': system},
            {'role': 'user', 'content': user_text},
        ]
    }).encode()
    req = urllib.request.Request(url, data=body,
        headers={'Authorization': auth_header, 'Content-Type': 'application/json'},
        method='POST')
    with urllib.request.urlopen(req, timeout=timeout) as r:
        d = json.loads(r.read())
    return d['choices'][0]['message']['content'].strip()

def _ask_ai(user_text: str, system: str) -> str:
    # 1) Google Gemini (free tier, no regional block)
    gemini_key = os.environ.get('GEMINI_API_KEY', '')
    if gemini_key:
        try:
            import urllib.request
            url = f'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={gemini_key}'
            body = json.dumps({
                'system_instruction': {'parts': [{'text': system}]},
                'contents': [{'parts': [{'text': user_text}]}],
                'generationConfig': {'maxOutputTokens': 300, 'temperature': 0.7}
            }).encode()
            req = urllib.request.Request(url, data=body,
                headers={'Content-Type': 'application/json'}, method='POST')
            with urllib.request.urlopen(req, timeout=15) as r:
                d = json.loads(r.read())
            return d['candidates'][0]['content']['parts'][0]['text'].strip()
        except Exception as e:
            print(f'Gemini error: {e}', file=sys.stderr)

    # 2) Groq
    groq_key = os.environ.get('GROQ_API_KEY', '')
    if groq_key:
        try:
            return _ask_openai_compat(
                'https://api.groq.com/openai/v1/chat/completions',
                f'Bearer {groq_key}', 'llama-3.1-8b-instant', system, user_text)
        except Exception as e:
            print(f'Groq error: {e}', file=sys.stderr)

    # 3) Anthropic Claude
    anthropic_key = os.environ.get('ANTHROPIC_API_KEY', '')
    if anthropic_key:
        try:
            import urllib.request
            body = json.dumps({
                'model': 'claude-haiku-4-5-20251001', 'max_tokens': 300,
                'system': system,
                'messages': [{'role': 'user', 'content': user_text}]
            }).encode()
            req = urllib.request.Request('https://api.anthropic.com/v1/messages', data=body,
                headers={'x-api-key': anthropic_key, 'anthropic-version': '2023-06-01',
                         'content-type': 'application/json'}, method='POST')
            with urllib.request.urlopen(req, timeout=15) as r:
                d = json.loads(r.read())
            return d['content'][0]['text'].strip()
        except Exception as e:
            print(f'Anthropic error: {e}', file=sys.stderr)

    # 4) Ollama (local, no internet needed) — longer timeout for cold start
    ollama_model = os.environ.get('OLLAMA_MODEL', '')
    if ollama_model:
        try:
            ollama_host = os.environ.get('OLLAMA_HOST', 'http://host.docker.internal:11434')
            return _ask_openai_compat(
                f'{ollama_host}/v1/chat/completions',
                'Bearer ollama', ollama_model, system, user_text, timeout=60)
        except Exception as e:
            print(f'Ollama error: {e}', file=sys.stderr)

    return ''

# ── Simple fallback (no API key) ──────────────────────────────────────────────
def _simple_reply(text: str, action: str, extra: str = '') -> str:
    if action == 'stop':    return 'Музыка остановлена.'
    if action == 'next':    return 'Переключаю на следующий трек.'
    if action == 'vol_up':  return 'Громкость увеличена.'
    if action == 'vol_down':return 'Громкость уменьшена.'
    if action == 'play':    return 'Включаю музыку.'
    if action == 'what':    return f'Сейчас играет: {extra}.' if extra else 'Музыка не воспроизводится.'
    hour = datetime.datetime.now().hour
    greet = 'Доброе утро' if hour < 12 else ('Добрый день' if hour < 18 else 'Добрый вечер')
    return f'{greet}! Для умных ответов добавьте ANTHROPIC_API_KEY в .env файл.'

# ── Main command processor ────────────────────────────────────────────────────
def process_command(text: str, campus: str = 'both') -> dict:
    t = text.lower().strip()
    action = None
    action_extra = ''

    # Execute campus control commands immediately (before Claude call)
    if _match(t, _STOP):
        _api('/api/stop')
        action = 'stop'
    elif _match(t, _NEXT):
        _api('/api/next')
        action = 'next'
    elif _match(t, _LOUDER):
        _api('/api/vol', data={'delta': 10, 'campus': campus})
        action = 'vol_up'
    elif _match(t, _QUIETER):
        _api('/api/vol', data={'delta': -10, 'campus': campus})
        action = 'vol_down'
    elif _match(t, _PLAY):
        _api('/api/play_random', data={'campus': campus})
        action = 'play'
    elif _match(t, _WHAT):
        action_extra = _fetch_track()
        action = 'what'

    # Build real-time context for Claude
    now = datetime.datetime.now()
    months_ru = ['января','февраля','марта','апреля','мая','июня',
                 'июля','августа','сентября','октября','ноября','декабря']
    ctx_lines = [
        f'Дата и время: {now.day} {months_ru[now.month-1]} {now.year}, {now.strftime("%H:%M")}.',
        'Местоположение: Баку, Азербайджан.',
    ]
    if _match(t, _WEATHER):
        w = _fetch_weather()
        if w:
            ctx_lines.append(f'Актуальная погода в Баку: {w}.')
    if action == 'what' and action_extra:
        ctx_lines.append(f'Сейчас в кампусе играет: {action_extra}.')
    elif action == 'what' and not action_extra:
        ctx_lines.append('Музыка в кампусе сейчас не воспроизводится.')
    if action and action != 'what':
        action_map = {
            'stop': 'Музыка остановлена.',
            'next': 'Переключено на следующий трек.',
            'vol_up': 'Громкость увеличена.',
            'vol_down': 'Громкость уменьшена.',
            'play': 'Музыка включена.',
        }
        ctx_lines.append(f'Только что выполнено: {action_map.get(action, "")}')

    system_prompt = (
        'Ты голосовой помощник умного кампуса в Баку — умный, дружелюбный, как Алиса от Яндекса. '
        'ВАЖНО: отвечай ТОЛЬКО на русском языке. Никаких китайских, арабских, азербайджанских или других иностранных слов — только русский. '
        'Ответ должен быть коротким: 1-3 предложения максимум. '
        'Ты можешь отвечать на любые вопросы: погода, время, факты, шутки, математика — всё что угодно. '
        'НЕ используй HTML теги, эмодзи, markdown — твои ответы озвучиваются голосом. '
        'Если тебе только что выполнили команду (стоп, следующий, громче и т.д.) — '
        'подтверди это естественным образом и можешь добавить что-то полезное. '
        '\n\nКонтекст:\n' + '\n'.join(ctx_lines)
    )

    reply = _ask_ai(text, system_prompt)
    if not reply:
        reply = _simple_reply(text, action, action_extra)

    return {'action': action or 'ai', 'reply': reply}

# ── TTS ───────────────────────────────────────────────────────────────────────
TTS_VOICE = 'ru-RU-SvetlanaNeural'

def tts(text: str, out_path: str) -> bool:
    clean = re.sub(r'<[^>]+>', '', text).strip()
    clean = re.sub(r'[^\w\s.,!?;:\'\"()\-–—а-яёА-ЯЁa-zA-Z0-9]', ' ', clean).strip()
    if not clean:
        return False
    try:
        import asyncio, edge_tts
        async def _gen():
            c = edge_tts.Communicate(clean, voice=TTS_VOICE, rate='+5%')
            await c.save(out_path)
        asyncio.run(_gen())
        return os.path.exists(out_path) and os.path.getsize(out_path) > 500
    except Exception as e:
        print(f'TTS error: {e}', file=sys.stderr)
        return False

# ── Entry point ───────────────────────────────────────────────────────────────
def handle_voice(audio_path: str, campus: str = 'both') -> dict:
    text = transcribe(audio_path)
    if text.startswith('[') and 'error' in text:
        return {'ok': False, 'text': '', 'reply': f'Ошибка распознавания речи.'}
    result = process_command(text, campus)
    result['ok'] = True
    result['text'] = text
    return result

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: voice_cmd.py <audio_file> [campus]')
        sys.exit(1)
    r = handle_voice(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else 'both')
    print(json.dumps(r, ensure_ascii=False, indent=2))
